# Generated by Django 4.2 on 2023-04-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles2', '0004_article_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish',
            field=models.DateField(null=True),
        ),
    ]
